# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: renovate

on:
  workflow_dispatch:
    branches:
      - master
  schedule:
    - branches:
        - master
      # POSIX cron syntax (UTC timezone)
      # https://docs.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events
      # https://crontab.guru/#0_3_*_*_2
      # At 11:00 on Tuesday (UTC+8)
      cron: '0 3 * * 2'

jobs:
  renovate:
    runs-on: ubuntu-latest
    env:
      # https://github.com/chalk/supports-color/blob/main/index.js#L21
      FORCE_COLOR: true

    steps:
      - name: Checkout
        # https://github.com/actions/checkout
        uses: actions/checkout@v2

      - name: Renovate
        # https://github.com/renovatebot/github-action
        uses: renovatebot/github-action@v25.35.5
        env:
          LOG_LEVEL: debug
        with:
          configurationFile: .github/workflows/renovate-action.js
          token: ${{ secrets.RENOVATE_TOKEN }}
